### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by copaah** [IMSY-DKFZ/htc#2]

**Comment by JanSellner** [comment]
Thank you for your interest in our work!
We have not forgotten this repository and are still actively working on it. However, there is still a bit of work to do on our side to make everything work as smoothly as possible and to deliver a good user experience.

We will inform you in this issue as soon as we have any updates.

**Comment by copaah** [comment]
@JanSellner thank you! Excited to see your work.

**Comment by copaah** [comment]
@JanSellner Just checking in again on this. Any ETA?

**Comment by JanSellner** [comment]
We are indeed very close to the finishing line and we hope that we can finally push it in the next two weeks!

So, thank you very much for your patience and stay tuned for just a little longer :-)

**Comment by JanSellner** [comment]
We are finally there :-)

You can now install our framework via PyPi (`pip install imsy-htc`) and experiment with our code/networks. The current release focuses on the [pretrained models](https://github.com/IMSY-DKFZ/htc#pretrained-models) so that you can use our networks to predict something on your data or use it for your own training.
